
from parser.models.biaffine_dependency_config import BertDependencyConfig
from parser.models.t2t_dependency_config import BertMrcT2TDependencyConfig
from parser.models.s2t_proposal_dependency_config import BertMrcS2TProposalDependencyConfig
from parser.models.s2t_query_dependency_config import BertMrcS2TQueryDependencyConfig

from parser.models.biaffine_dependency_parser import BiaffineDependencyParser
from parser.models.t2t_dependency_parser import BiaffineDependencyT2TParser
from parser.models.s2t_proposal_dependency_parser import BiaffineDependencyS2TProposalParser
from parser.models.s2t_query_dependency_parser import BiaffineDependencyS2TQeuryParser
